code --install-extension Asuka.insertnumbers
code --install-extension Stephanvs.dot
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension chrmarti.regex
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension emilast.LogFileHighlighter
code --install-extension fabiospampinato.vscode-terminals
code --install-extension fms-cat.theme-monokaisharp
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-Wombat
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension humao.rest-client
code --install-extension IBM.XMLLanguageSupport
code --install-extension ionicabizau.ms-dos-editor-theme
code --install-extension jbenden.c-cpp-flylint
code --install-extension jebbs.plantuml
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension kaiwood.better-line-select
code --install-extension mkloubert.vscode-kanban-neo
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-vscode.Theme-1337
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.markdown-checkbox
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ryu1kn.partial-diff
code --install-extension shanoor.vscode-nginx
code --install-extension sleistner.vscode-fileutils
code --install-extension slevesque.vscode-hexdump
code --install-extension thenikso.github-plus-theme
code --install-extension TomasHubelbauer.vscode-markdown-todo
code --install-extension vector-of-bool.gitflow
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
